import Link from "next/link";
import { ArrowUpRight, Database, ExternalLink, FileCheck2, Mail, Radio, ShieldCheck } from "lucide-react";
import { PageHero } from "@/components/common/PageHero";
import { siteConfig } from "@/config/site";
import { tdk } from "@/seo/tdk";
import styles from "@/style/page/legal/legal.module.css";

type LegalTdkKey = "about" | "contact" | "privacy" | "terms" | "copyright";
type LegalSection = { title: string; paragraphs: string[]; links?: { label: string; href: string }[] };
type InfoPage = { title: string; eyebrow: string; description: string; tdkKey: LegalTdkKey; sections: LegalSection[] };

export const legalPages: Record<string, InfoPage> = {
  "about-us": {
    title: "About WARDOGS Field Intel", eyebrow: "Independent player resource", tdkKey: "about", description: tdk.about.description,
    sections: [
      { title: "Frontline Pathfinder", paragraphs: ["Frontline Pathfinder is the editorial and research team behind WARDOGS Field Intel. It began in early 2026 as a small group of independent-game players and technical-minded researchers who wanted a better way to document systems that reward preparation, careful observation and tactical decision-making.", "The team was formed around a familiar player frustration: many game guides repeat surface-level information, bury the actionable answer under filler, or treat untested claims as fact. For a game where a wrong caliber, an incompatible attachment or a careless cash spend can change the next deployment, that approach is not good enough.", "Frontline Pathfinder is not an official developer, data provider or representative of WARDOGS. It is an independent editorial identity built around disciplined player research, clear writing and a willingness to mark uncertainty honestly."] },
      { title: "Why WARDOGS Field Intel exists", paragraphs: ["WARDOGS Field Intel exists to make the moments between deployments easier to read. Players should be able to check a weapon relationship, price a kit, understand a system or catch up on a patch without opening a chain of thin pages or guessing which number is current.", "The site is designed around real pre-match questions: Does this magazine fit the selected weapon? What does this life cost if it goes wrong? Which role is missing from the squad? What changed before tonight’s session? The answer should be direct, traceable and useful at the point of decision.", "This is not an official WARDOGS website. It is not owned, operated, sponsored, approved or endorsed by the game’s developers, publishers, licensors or other rights holders. Official game materials are referenced only for identification, commentary and player education."] },
      { title: "Experience-driven research", paragraphs: ["Frontline Pathfinder treats first-hand play, repeatable checks and careful comparison as the starting point for useful game writing. A guide should explain a practical route through a system, not merely restate its name. An item record should make the next equipment decision easier, not create the illusion of certainty around a value that has not been confirmed.", "Where a behavior can be checked in the live game, the preferred process is to test it more than once, compare it against the currently recorded relationship, and state the build context when it matters. Where direct verification is unavailable, the record should identify the limit of what is known rather than fill the gap with a plausible answer."] },
      { title: "Structured delivery, not filler", paragraphs: ["Every section is intended to earn its place. Guides use direct answers, practical routines, route checks and decision points so a player can find the immediate answer first and read deeper only when needed. The Wiki keeps the core comparison values on the list page because players should not need to open a separate detail screen just to find a price or caliber.", "The Builder follows item compatibility from the selected weapon outward. Tools are deliberately narrow: they help compare weapons or plan a spend instead of promising a universal answer. This structure is meant to respect a player’s time while still giving them enough context to make the choice themselves."], links: [{ label: "Browse the WARDOGS Wiki", href: "/wiki" }, { label: "Open the Loadout Builder", href: "/builder" }] },
      { title: "Editorial standards and independence", paragraphs: ["A game in active development changes quickly, and a clean-looking number can still be wrong. Site copy separates recorded data, observed behavior and editorial judgment where possible. An unknown value is not silently converted to zero, and a community observation is not presented as a confirmed game rule.", "Tier placements and guide recommendations are viewpoints, not paid placements, official rankings or promises of performance. The project does not sell access to favorable coverage, and it does not change a record to match a preferred outcome. If a recommendation depends on map context, squad composition, player skill or a changing build, that dependency should be visible in the writing."] },
      { title: "Corrections, updates and accountability", paragraphs: ["When a patch changes an item, price or relationship, related lists and tools should be reviewed together. The Updates page is maintained as a readable timeline of listed versions and player-relevant changes. A date on an item record reflects the most recent check recorded for that entry; it does not guarantee that the live game has not changed since then.", "Useful correction reports name the exact page, identify the value or relationship at issue, state the build or date observed, and include a public source or reproducible check when available. Broad claims without a page or context are difficult to verify, while a focused report can improve the record for everyone."], links: [{ label: "Read the update timeline", href: "/updates" }, { label: "Send a correction", href: "/legal/contact-us" }] },
      { title: "Official information and support", paragraphs: ["For official release announcements, account support, purchase questions, platform issues, game rules and moderation matters, use the channels published by the WARDOGS rights holders. Field Intel is a companion player resource, not a substitute for official support or an official announcement.", "External links are provided for convenience. Their availability, content and policies are controlled by their respective operators."], links: [{ label: "WARDOGS on Steam", href: siteConfig.steamUrl }, { label: "Official announcements", href: "https://steamcommunity.com/app/1867240/announcements/" }] },
    ],
  },
  "contact-us": {
    title: "Contact WARDOGS Field Intel", eyebrow: "Corrections, attribution and rights", tdkKey: "contact", description: tdk.contact.description,
    sections: [
      { title: "How to contact the project", paragraphs: ["The project can be contacted by email for factual corrections, broken pages, attribution questions, rights requests and other site-related matters. This contact channel is for the website itself; it cannot provide official WARDOGS customer support, restore game access, investigate in-game conduct or resolve purchases made through another service.", `Send messages to ${siteConfig.contactEmail}. Email is used instead of an on-site form so visitors can decide what information to include and retain a copy of their own correspondence.`], links: [{ label: siteConfig.contactEmail, href: `mailto:${siteConfig.contactEmail}?subject=WARDOGS%20Field%20Intel` }] },
      { title: "Reporting a data or content issue", paragraphs: ["For an item value, compatibility relationship, outdated guide or tool issue, include the page URL, the specific claim that needs attention, the game build or date you observed, and any public evidence that makes the issue reproducible. Screenshots are most useful when they show the relevant game version and value, rather than only a cropped result.", "Reports should focus on player-facing information that may be checked responsibly. Do not send account credentials, personal account records, private test assets, leaked material, or information you are not permitted to disclose. The site may decline to publish or act on information that cannot be verified lawfully and responsibly."] },
      { title: "Source handling and editorial review", paragraphs: ["A link, screenshot or message sent to the project is a lead for review, not automatic proof. Editors may compare it against the live game, an official announcement, a public source or other reproducible evidence before changing a record. This matters most for prices, hidden relationships, patch effects and mechanics that can change without a visible version label.", "When a report identifies a real issue, the goal is to correct the connected player experience rather than only alter one sentence. Depending on the evidence, that can include the Wiki list, Builder compatibility, a guide callout, a tool description or an update note."] },
      { title: "Copyright, trademark and attribution requests", paragraphs: ["If you represent a rights holder and believe an asset, passage, label or attribution needs attention, identify the exact URL and material, provide your name and authority to act, describe the concern, and state the action requested. Clear notices can be reviewed more quickly than a general claim with no location or supporting context.", "Receiving a request does not mean that every claim is accepted or that a particular legal status is conceded. The project will review good-faith notices, seek clarification when necessary, and take an appropriate action based on the information available."], links: [{ label: "Read the Copyright Notice", href: "/legal/copyright" }] },
      { title: "What to expect", paragraphs: ["Messages are reviewed when reasonably possible. A response time is not guaranteed, and a response may be limited where a report lacks sufficient detail, concerns an external service, asks for legal advice, or requests action outside the site’s control.", "This mailbox is not a secure channel. Please do not include sensitive personal information, payment details, passwords or information that could put another player at risk. By sending a message, you understand that the project may retain the correspondence as reasonably necessary to respond, maintain records and protect the site." ] },
      { title: "Respectful communication", paragraphs: ["The contact channel is intended for specific, good-faith communication about the site. Threatening, abusive, repetitive or automated messages may be filtered, retained for security purposes or left unanswered. Disagreement with an editorial recommendation is useful when tied to a specific claim or player-facing alternative; personal attacks are not.", "For an urgent issue involving the official game, a platform account or a safety concern, contact the relevant official platform or rights holder. WARDOGS Field Intel cannot access their systems or act on their behalf." ] },
    ],
  },
  "privacy-policy": {
    title: "Privacy Policy", eyebrow: "Plain-language privacy", tdkKey: "privacy", description: tdk.privacy.description,
    sections: [
      { title: "Scope and effective date", paragraphs: ["This Privacy Policy explains how WARDOGS Field Intel handles information when you visit wardogs.com and use its player reference pages, search, Builder and tools. It applies to this website only. It does not apply to Steam, social platforms, official WARDOGS services, advertising networks, or any other website linked from this site.", "The current version is effective September 11, 2026. It describes the site as it operates today. If the project later adds accounts, comments, analytics, advertising, a contact form, payments or another data-processing service, this policy will be reviewed and updated to reflect that change." ] },
      { title: "Information used in the site interface", paragraphs: ["WARDOGS Field Intel does not offer player accounts, registration, comments, direct messaging or on-site contact forms. Search terms, selected kit items and calculator values are used in the browser to provide the requested interface result. The current implementation does not intentionally create a first-party user profile from those inputs.", "Some shareable links may include selected item identifiers or display preferences in the URL. Anyone who receives such a link can see those parameters. Do not put your name, account identifier, contact details or other personal information into a query field or shareable URL." ] },
      { title: "Routine technical and hosting information", paragraphs: ["Like most public websites, the service that hosts and delivers the site may process ordinary technical information such as an IP address, browser and device characteristics, request time, requested URL, referring page and diagnostic data. This information may be used by the hosting provider for delivery, security, abuse prevention, performance and operational troubleshooting.", "WARDOGS Field Intel does not control the infrastructure provider’s independent practices. Where hosting providers process information for their own service operations, their terms and privacy notices apply. The site administrator should only access or use operational information when reasonably necessary to run, secure or improve the site." ] },
      { title: "Email correspondence and retention", paragraphs: ["If you contact the project by email, the message and the information you choose to include may be processed to read, respond to, investigate and document the request. That can include your email address, the page URL you mention, attachments and the conversation history. Please do not include sensitive information that is not needed for the request.", "Correspondence may be retained for as long as reasonably needed to resolve the issue, preserve a record of a rights or safety request, prevent repeated abuse, or meet an applicable obligation. The project does not sell email correspondence or use it to build an advertising profile." ] },
      { title: "Cookies, local storage and external services", paragraphs: ["The current site is not designed to set first-party advertising or account-tracking cookies. Browser storage may be used only where needed for ordinary display or interface behavior. Your browser, extensions, device, hosting provider or a linked external service may nevertheless use their own storage or technical identifiers outside the project’s control.", "Links to Steam and other external services open resources operated by third parties. Once you leave wardogs.com, that service’s privacy policy, cookie controls and terms govern your activity. Review those policies before providing information or enabling a third-party connection." ] },
      { title: "Choices, requests and contact", paragraphs: ["You can control many routine web technologies through your browser settings, including cookies, stored data and referral behavior. Clearing browser data may remove locally retained display preferences or shared tool selections. Because the current site does not create member accounts, there is no account dashboard or profile to access, correct or delete.", `For a privacy question or a request concerning correspondence you sent directly to the project, email ${siteConfig.contactEmail}. The project will evaluate requests in light of the information available, applicable obligations and the need to preserve reasonable security and operational records.`], links: [{ label: siteConfig.contactEmail, href: `mailto:${siteConfig.contactEmail}?subject=Privacy%20Question` }] },
      { title: "Security and policy updates", paragraphs: ["Reasonable technical and organizational measures are used to protect the site and its operations, but no public internet service can promise absolute security. Keep browsers and devices updated, use caution with external links, and avoid sending sensitive information to the project email address.", "A revised policy will be posted on this page with a new effective date when a material operational change affects information handling. Continued use of the site after publication means you are using the site under the then-current policy, subject to rights that cannot lawfully be waived by notice." ] },
    ],
  },
  "terms-of-service": {
    title: "Terms of Service", eyebrow: "Use the site fairly", tdkKey: "terms", description: tdk.terms.description,
    sections: [
      { title: "Acceptance and purpose", paragraphs: ["These Terms of Service govern your use of wardogs.com and its publicly available WARDOGS Field Intel pages. By accessing or using the site, you agree to use it in accordance with these terms. If you do not agree, do not use the site.", "The site is an independent player reference. Its item lists, guide recommendations, rankings, summaries and tool results are provided to help players evaluate options. They are not official WARDOGS instructions, a promise of accuracy, a guarantee of in-game outcome, or a substitute for information published by the game’s rights holders." ] },
      { title: "Data, editorial judgments and Early Access", paragraphs: ["WARDOGS can change through patches, server-side adjustments and Early Access development. A listed price, stat, compatibility relationship or system description may be incomplete, superseded or incorrect despite reasonable efforts to keep records current. Use the live game and official announcements to confirm a decision that matters to you.", "Tier placements and guide recommendations are editorial judgments made for a particular player context. They should be read as a starting point for comparison, not as an instruction to buy a specific item, spend all available cash, take a particular route or copy a kit without considering the match." ] },
      { title: "Permitted use", paragraphs: ["You may browse, link to and share public pages for personal, educational and community reference. You may quote limited portions of original text with clear attribution and a link back to the relevant page. These permissions do not transfer ownership of the site, its original writing, its interface or its code.", "You may not use the site in a way that disrupts availability, bypasses access controls, probes infrastructure, introduces malware, harvests data at a rate that affects service, impersonates the project, or falsely presents content as official WARDOGS material. You may not use the site to distribute private, leaked, unlawful or rights-infringing material." ] },
      { title: "Third-party content and links", paragraphs: ["WARDOGS game names, artwork, screenshots, logos and other official materials are owned by their respective rights holders. Their appearance on this fan site is for identification, commentary and player reference. The project does not claim ownership of those materials or any relationship with their owners.", "The site may link to third-party pages for official information or convenience. It does not control, endorse or guarantee the availability, security, accuracy or policies of those sites. Your use of a third-party service is governed by its own terms and privacy practices." ] },
      { title: "Feedback and suggestions", paragraphs: ["If you voluntarily send a correction, idea or suggestion, you understand that the project may review it without an obligation to use it, compensate you or keep it confidential. This does not transfer ownership of your original material; it simply allows the project to consider the feedback when improving player-facing content.", "Do not submit confidential business information, private game materials, passwords, personal records or content that you do not have the right to share. The project may remove, ignore or report submissions that create a safety, privacy or rights concern." ] },
      { title: "Availability, changes and limitations", paragraphs: ["The project may revise, correct, add, remove or discontinue any page, feature or item record at any time. Access may be unavailable due to maintenance, hosting conditions, security work or circumstances outside the project’s control. No uninterrupted service level is promised.", "To the fullest extent permitted by applicable law, the project maintainers are not liable for in-game losses, missed opportunities, purchase decisions, data loss or other consequences arising from use of, inability to use, or reliance on this independent player resource. These terms are not legal advice and do not limit rights that cannot lawfully be excluded." ] },
    ],
  },
  copyright: {
    title: "Copyright Notice", eyebrow: "Fan-site attribution", tdkKey: "copyright", description: tdk.copyright.description,
    sections: [
      { title: "Independent fan-site notice", paragraphs: ["WARDOGS Field Intel is an independent fan site. WARDOGS, associated game names, logos, artwork, screenshots, characters, audio-visual materials and other official assets are the property of their respective owners. Their appearance here is intended to identify the game and support commentary, criticism, player education and factual reference.", "Nothing on this website states or implies a partnership, endorsement, sponsorship, authorization or official connection with the WARDOGS developers, publishers, licensors or other rights holders. All rights in official WARDOGS materials remain with their respective owners." ] },
      { title: "Original site materials", paragraphs: ["Unless a page says otherwise, WARDOGS Field Intel retains rights in its original writing, layout, organization, visual treatment and tool logic. Factual game data is not claimed as an original creative work; the site’s original contribution is the selection, arrangement, explanation and player-facing presentation of that information.", "You may link to public pages and quote limited excerpts with clear attribution. Republishing substantial original site copy, recreating the site’s presentation, or redistributing its original tools without permission may require prior written consent." ] },
      { title: "Trademarks and attribution", paragraphs: ["Names and marks used to identify WARDOGS or related products may be trademarks of their respective owners. Use of a mark on this site is nominative and descriptive: it tells players which game and materials are being discussed. It does not grant a license to use that mark or suggest that the mark owner approves this project.", "Where a specific creator, photographer, source or rights owner is known for material used on the site, the project aims to preserve appropriate attribution. If an attribution is missing or inaccurate, please provide the precise page and corrected credit information." ] },
      { title: "Rights-holder requests", paragraphs: ["A rights holder or authorized representative who believes material should be removed, corrected, credited differently or reviewed should email the exact URL, identify the relevant material, provide contact information and authority to act, explain the basis of the request, and state the requested action. Notices that are specific and verifiable can be reviewed more efficiently.", "This contact channel is not a representation that the site has registered a designated agent, qualified for any particular statutory safe harbor, or adopted a legal conclusion about any claim. The project may seek clarification, request supporting information, or take a reasonable interim action while reviewing a good-faith notice."], links: [{ label: "Contact WARDOGS Field Intel", href: "/legal/contact-us" }] },
      { title: "Review approach", paragraphs: ["The project aims to treat credible requests with care and without unnecessary delay. Depending on the issue, a response may involve correcting a credit, replacing an asset, adding context, temporarily limiting access to a page, or declining a request where the available information does not support it. A review outcome is not legal advice and does not determine the rights of any party.", "If a request is incomplete, the project may ask for a more precise URL, proof of authority, a clearer identification of the work, or an explanation of the requested remedy. This helps avoid removing the wrong material or misattributing a work." ] },
      { title: "Reporting misuse of this site’s work", paragraphs: ["If you believe original WARDOGS Field Intel content has been copied in a way that misrepresents the project or omits attribution, send the destination URL, the original page URL and a short explanation of the concern. The project will review the report and may contact the relevant operator where appropriate.", `Copyright © ${new Date().getFullYear()} ${siteConfig.name}. All rights reserved.`] },
    ],
  },
};

export const legacyLegalPaths: Record<string, string> = { about: "/legal/about-us", contact: "/legal/contact-us", privacy: "/legal/privacy-policy", terms: "/legal/terms-of-service", copyright: "/legal/copyright" };
const icons = [Database, ShieldCheck, FileCheck2, Radio];

export function LegalPage({ slug }: { slug: string }) {
  const page = legalPages[slug];
  return <main id="main-content">
    <PageHero eyebrow={page.eyebrow} title={page.title} description={page.description} image="/images/official/wardogs-13.jpg" crumbs={[{ label: "Legal", href: "/legal/about-us" }, { label: page.title }]} />
    <section className={`container ${styles.layout}`}>
      <article className={styles.document}>{page.sections.map((section, index) => { const Icon = icons[index % icons.length]; return <section key={section.title}><div className={styles.number}><Icon aria-hidden="true" /><span>{String(index + 1).padStart(2, "0")}</span></div><div><h2>{section.title}</h2>{section.paragraphs.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}{section.links && <div className={styles.links}>{section.links.map((link) => <Link key={link.href} href={link.href}>{link.label}{link.href.startsWith("http") || link.href.startsWith("mailto:") ? <ExternalLink size={13} /> : <ArrowUpRight size={13} />}</Link>)}</div>}</div></section>; })}</article>
      <aside className={styles.rail}><Mail aria-hidden="true" /><span>Project desk</span><h2>Independent. Useful. Correctable.</h2><p>Send a page URL and enough context to check it properly. This site is maintained for WARDOGS players, not as an official game service.</p><a href={`mailto:${siteConfig.contactEmail}`}>{siteConfig.contactEmail}</a><small>Last policy review · September 11, 2026</small></aside>
    </section>
  </main>;
}
